routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::match(['get', 'post'],'/', function () {
    $request = request();
    if ($request->isMethod('POST')) {
        request()->validate([
            'name' => 'cnpj'
        ]);
        return 'ok';
    }
    return view('welcome');
});

Route::group([
    'prefix' => 'admin/tags',
    'as' => 'tags.',
    'namespace' => 'Admin',
], function () {
    Route::get('/{tag?}', 'TagsController@index')->name('index');
    Route::post('/store', 'TagsController@store')->name('store');
    Route::put('/update/{tag}', 'TagsController@update')->name('update');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Rockbuzz\LaraActivities\Traits\RecordsActivity;

class Category extends Model
{
    use RecordsActivity;

    protected $fillable = ['name', 'metadata'];

    protected $casts = ['metadata' => 'array'];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Rockbuzz\LaraActivities\Traits\RecordsActivity;

class User extends Authenticatable
{
    use Notifiable, RecordsActivity;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/TagsController.php
<?php

namespace App\Http\Controllers\Admin;

use Rockbuzz\LaraTags\Models\Tag;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\TagRequest;

class TagsController extends Controller
{
    private $tag;

    public function __construct(Tag $tag)
    {
        $this->tag = $tag;
    }

    public function index(Tag $tag = null)
    {
        $tags = $this->tag->latest()->get();

        if (request()->expectsJson()) {
            return $tags;
        }

        return view('tags.index', compact('tags', 'tag'));
    }

    public function store(TagRequest $request)
    {
        $tag = $this->tag->create($request->validated());

        if (request()->expectsJson()) {
            return $tag;
        }

        return redirect()->route('tags.index')
            ->withSuccess('Tag criada com sucesso!');
    }

    public function update(Tag $tag, TagRequest $request)
    {
        $tag = $tag->update($request->validated());

        if (request()->expectsJson()) {
            return $tag;
        }

        return redirect()->route('tags.index')
            ->withSuccess('Tag atualizada com sucesso!');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Laravel</title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">

    <!-- Styles -->
    <link type="text/css" rel="stylesheet" href="{{ mix('css/app.css') }}">
</head>

<body>
    <div>
        <section class="container pt-5 pb-5">
            @include('layouts.alert')
            @yield('content')
        </section>
    </div>

    <script src="{{ mix('js/app.js') }}"></script>
</body>

</html>

resources/views/layouts/alert.blade.php
@if (session('success'))
<div class="alert alert-success alert-dismissible fade show" role="alert">
    {{ session('success')}}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
@endif

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/tags/includes/form.blade.php
<form method="post" action="{{ !empty($tag) ? route('tags.update', $tag) :route('tags.store') }}" enctype="multipart/form-data">
    @csrf
    @if(!empty($tag))
    @method('put')
    @endif

    <div class="card text-left">
        <h3 class="card-header">
            @if(!empty($tag))
            Editando Tag: <strong>{{ $tag->name }}</strong>
            @else
            Criar Tag
            @endif
        </h3>
        <div class="card-body">
            <div class="form-group {{ $errors->has('name') ? 'has-error' : null }}">
                <label>
                    <small class="text-danger">*</small>
                    Nome:
                </label>
                <input type="text" name="name" value="{{ old('name') ?? $tag->name ?? null }}" class="form-control" placeholder="Informe o nome">
                @if($errors->has('name'))
                <div class="help-block">
                    {{ $errors->first('name') }}
                </div>
                @endif
            </div>
            <div class="form-group {{ $errors->has('metadata.description') ? 'has-error' : null }}">
                <label>
                    <small class="text-danger">*</small>
                    Descrição:
                </label>
                <textarea maxlenght="155" name="metadata[description]" value="{{ old('description') ?? $tag->metadata->description ?? null }}" class="form-control">{{ old('metadata.description', $tag->metadata->description ?? null) }}</textarea>
                @if($errors->has('metadata.description'))
                <div class="help-block">
                    {{ $errors->first('metadata.description') }}
                </div>
                @endif
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group {{ $errors->has('metadata.background') ? 'has-error' : null }}">
                        <label>
                            Cor de fundo:
                        </label>
                        <input type="color" name="metadata[background]" value="{{ old('metadata.background') ?? $tag->metadata->background ?? '#000' }}" class="form-control">
                        @if($errors->has('metadata.background'))
                        <div class="help-block">
                            {{ $errors->first('metadata.background') }}
                        </div>
                        @endif
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group {{ $errors->has('metadata.font_color') ? 'has-error' : null }}">
                        <label>
                            Cor da fonte:
                        </label>
                        <input type="color" name="metadata[font_color]" value="{{ old('metadata.font_color') ?? $tag->metadata->font_color ?? '#fff' }}" class="form-control">
                        @if($errors->has('metadata.font_color'))
                        <div class="help-block">
                            {{ $errors->first('metadata.font_color') }}
                        </div>
                        @endif
                    </div>
                </div>
            </div>
            <div class="form-group {{ $errors->has('type') ? 'has-error' : null }}">
                <label>
                    <small class="text-danger">*</small>
                    Tipo:
                </label>
                <select class="form-control" name="type">
                    <option {{old('type') == 'global' || !empty($tag) && $tag->type == 'global' ? 'selected' : null}} value="global">Global</option>
                    <option {{old('type') == 'category' || !empty($tag) && $tag->type == 'category' ? 'selected' : null}} value="category">Category</option>
                </select>
                @if($errors->has('type'))
                <div class="help-block">
                    {{ $errors->first('type') }}
                </div>
                @endif
            </div>

            @if(!empty($tag))
            <button class="btn btn-primary float-left">
                <i class="far fa-save"></i>
                Atualizar
            </button>
            @else
            <button class="btn btn-success float-left">
                <i class="far fa-save"></i>
                Criar
            </button>
            @endif
        </div>
    </div>
</form>

resources/views/tags/includes/table.blade.php
<div class="table-responsive">
    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th>Name</th>
            <th>Type</th>
            <th width="1px"><i class="fa fa-cog"></i></th>
        </tr>
        </thead>
        <tbody>
        @foreach($tags as $tag)
            <tr>
                <td>{{ $tag->name }}</td>
                <td>{{ $tag->type }}</td>
                <td><a href="{{ route('tags.index', $tag->slug) }}"><i class="fa fa-cog"></i></a></td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>

resources/views/tags/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
    <div class="col-md-4 col-12">
        @include('tags.includes.form')
    </div>
    <div class="col-md-8 col-12">
        <div class="card">
                <h3 class="card-header">Lista de Tags</h3>
            <div class="card-body">
                @include('tags.includes.table')
            </div>
        </div>
    </div>
</div>
@endsection